export const DIAGNOSIS_LIST = [
    "TERMINAL DEGEN", "EXIT LIQUIDITY", "PAPER HANDS", "RUG COLLECTOR", "GAS GUZZLER", "NFT BAGHOLDER", "SOLANA SIMP", "MEMECOIN VICTIM", "FARMING BOT", "HODL COPE",
    "DEV DONATOR", "CHART STARER", "LIQUIDATED", "POOR", "WHALE (DEROGATORY)", "ETH MAXI IN DENIAL", "BRIDGE TROLL", "AIRDROP BEGGAR", "WALLET DRAINER TARGET", "HONEYPOT TESTER",
    "BUY HIGH SELL LOW", "FOMO PATIENT", "COPE ADDICT", "JEET SURVIVOR", "CEX REFUGEE", "STABLECOIN HOLDER", "LP PROVIDER (REKT)", "IMPERMANENT LOSS GOD", "SCAM CLICKER", "DISCORD MOD",
    "PUMP FUN VICTIM", "RAYDIUM DONOR", "MEV BOT FOOD", "SOLSCAN STALKER", "TX FAILED WIZARD", "RPC ERROR PIONEER", "SLIPPAGE VICTIM", "FRONT RUNNED", "SANDWICHED", "RUGGED AGAIN",
    "DIAMOND HANDS (BAGS)", "VAPORWARE INVESTOR", "WHITEBIT USER", "BINANCE INTERN", "COINBASE KYC VICTIM", "LEDGER LEAKER", "METAMASK STRUGGLER", "PHANTOM GHOST", "SOLFLARE SIMP", "MAGIC EDEN WHALE",
    "TENSOR TRADER", "JUPITER FARMER", "DRIFT LIQUIDATED", "MARGIN CALL RECEIVER", "LEVERAGE ADDICT", "100X CHASER", "0X SURVIVOR", "TOKEN SNIPER (FAILED)", "COPY TRADER (REKT)", "INFLUENCER FOLLOWER",
    "TELEGRAM SHILL", "TWITTER REPLY GUY", "GIVEAWAY BOT", "DISCORD BEGGAR", "WHITELIST GRINDER", "MINT FAILED", "GAS POOR", "SOLANA BEACH BUM", "BLOCKCHAIN TOURIST", "SEED PHRASE LEAKER",
    "HOT WALLET RISKER", "COLD STORAGE PARANOID", "MULTISIG HOSTAGE", "DAO VOTER (IGNORED)", "GOVERNANCE CLOWN", "PROPOSAL SPAMMER", "STAKING JAIL", "UNSTAKING WAITER", "EPOCH WATCHER", "VALIDATOR SIMP",
    "TIKTOK INVESTOR", "YOUTUBE SIGNAL FOLLOWER", "REDDIT ADVICE TAKER", "4CHAN BIZ READER", "WARREN BUFFETT HATER", "DAVE PORTNOY CLONE", "JIM CRAMER VICTIM", "ELON MUSK REPLY GUY", "DOGE HOLDER", "SHIB SURVIVOR",
    "BONK LATE BUYER", "WIF FUMBLER", "POPCAT SELLER", "MOGGED", "LOOKS RARE (IT'S NOT)", "RIGHT CLICK SAVER", "METADATA REFRESHER", "FLOOR PRICE WATCHER", "TRAIT SNIPER (MISSED)", "RARITY TOOLS SLAVE"
];

export const ROASTS_WHALE = [
    "Oh look, a whale! 🐋 Or just someone who bought SOL at $8 and forgot to sell.",
    "Money can't buy happiness, and judging by your tx history, it can't buy wins either.",
    "You have enough capital to move the market, but you use it to buy rug pulls.",
    "Nice liquidity. Shame about the execution.",
    "Are you washing trading or just really bad at this?",
    "Whale alert 🚨 Proceed to dump on this guy.",
    "Your wallet size compensates for... something else.",
    "Smart money? No. Just a lot of money.",
    "You're the reason we need wealth taxes.",
    "Big bags, smooth brain.",
    "You have enough SOL to buy a house, but you live in the memecoin trenches.",
    "Proof that you don't need IQ to have liquidity.",
    "A whale in the ocean of incompetence.",
    "You're not a market maker, you're a market donor.",
    "Imagine having this much SOL and still losing money on fees.",
    "Your accountant must hate you.",
    "I bet you pay for Twitter Blue.",
    "Rich enough to lose, too poor to win.",
    "You provide the exit liquidity for the rest of us. Thank you for your service.",
    "Is this an exchange wallet? Because you're holding everyone's bags.",
    "You're the target demographic for every scam in the book.",
    "More dollars than sense.",
    "You could have retired, but you chose to gamble on cartoons instead.",
    "Your portfolio graph looks like a crime scene investigation.",
    "Have you ever heard of a 'stop loss' or do you just enjoy pain?",
    "You buy tops like it's a hobby.",
    "Sell signal: This guy just bought.",
    "You're the reason why devs rug.",
    "Stop trading. Just stake it and go outside.",
    "I've seen smarter bots than you."
];

export const ROASTS_PLEB = [
    "Your wallet has less value than a used napkin. 0.01 SOL? Really?",
    "I've seen faucets with more liquidity than this wallet.",
    "You can't even afford the gas to be roasted properly.",
    "Is this a burner wallet or are you just this broke?",
    "0.01 SOL? Don't spend it all in one transaction.",
    "There are dust attacks worth more than your entire portfolio.",
    "You're not HODLing, you're just trapped by gas fees.",
    "Your financial freedom is currently priced at $1.50.",
    "OnlyFans subscriptions are not an investment strategy.",
    "McDonald's is hiring, just saying.",
    "This wallet screams 'I started trading yesterday'.",
    "You're trading with lunch money.",
    "Did you get this SOL from a faucet?",
    "Your bag is so light it floats.",
    "You're the definition of 'exit liquidity' for ants.",
    "Even the blockchain feels bad for storing this balance.",
    "You call this a portfolio? I call it a cry for help.",
    "Are you saving up for a singular transaction?",
    "Gas fees are your biggest expense.",
    "You couldn't rug pull a hamster.",
    "Holding dust like it's gold dust.",
    "Please deposit more funds to continue being roasted.",
    "Error 404: Funds not found.",
    "You're playing on expert mode with that balance.",
    "Just give up and buy an index fund.",
    "Your wallet is an insult to the Solana network.",
    "Proof of Work? No, Proof of Poverty.",
    "You're the reason networks have minimum transaction limits.",
    "I'd hack you, but the gas fee would cost more than your balance.",
    "Have you tried... earning money?"
];

export const ROASTS_DEGEN = [
    "Touch grass. You're trading more than a bot.",
    "Your transaction history is longer than a CVS receipt.",
    "Do you ever sleep? Or just stare at DexScreener?",
    "You've paid more in gas fees than you've made in profit.",
    "Degen score: Terminal. Diagnosis: incurable gambling addiction.",
    "Scanning for alpha... none found. Just shitcoins.",
    "You are the exit liquidity. Every. Single. Time.",
    "Your strategy is 'buy high, sell low' formatted as code.",
    "Congratulations, you funded the dev's new Lambo.",
    "I smell desperation and failed memecoins.",
    "You trade like you have free healthcare.",
    "How many rugs can one person endure?",
    "Your wallet sees more action than you do.",
    "Stop trying to snipe. You're the one getting sniped.",
    "You're addicted to red candles.",
    "Is your strategy 'random walk down Wall Street' but drunk?",
    "You click links in Discord DMs, don't you?",
    "Your risk management is non-existent.",
    "You'd leverage trade water in a desert.",
    "Every transaction is a cry for dopamine.",
    "You're not a trader, you're a donor.",
    "The house always wins, and you are definitely not the house.",
    "You have the attention span of a goldfish on adderall.",
    "Stop refreshing the chart. It's going to zero.",
    "You bought the top. Again. Incredible consistency.",
    "Your PnL is a phone number... with a minus sign.",
    "You're single-handedly keeping the Solana validators rich.",
    "You're chasing pumps like a dog chasing cars.",
    "Have you considered a career in not losing money?",
    "Your trading bot is broken. Oh wait, that's you."
];

export const ROASTS_PAPERHAND = [
    "Paper hands detected. 🧻 Your ancestors are ashamed.",
    "Sold the bottom again? Classic.",
    "HODLing is hard when you have the spine of a jellyfish.",
    "You sell faster than a dev with unlocked tokens.",
    "Weak hands. Weak mindset. Weak wallet.",
    "Did you panic sell? Or did you just hate money?",
    "Diamond hands? More like damp tissue hands.",
    "You folded faster than a lawn chair.",
    "Buy high, panic sell low. The circle of life.",
    "The market thanks you for your donation.",
    "You couldn't hold a winning trade if it was glued to your hands.",
    "Panic seller of the year award goes to...",
    "You saw a 1% dip and sold everything. Pathetic.",
    "Your conviction is weaker than shared Wifi.",
    "You sell right before the pump. Every time. It's a talent.",
    "The moment you sell, it goes up. Thank you for your sacrifice.",
    "You have an allergy to profit.",
    "Stop looking at the 1-minute chart, you coward.",
    "You're the reason we have volatility.",
    "Your hands are made of lettuce.",
    "You're shaking out yourself.",
    "Imagine selling your bags for a loss. Couldn't be me. Oh wait, it's you.",
    "You donate to the strong hands.",
    "Fear is your only strategy.",
    "You need a prescription for Xanax before you trade again.",
    "Sold at the bottom? Check. Regret? Check.",
    "You are the capitulation wick.",
    "Soft hands, empty wallet.",
    "Just delete the app when it dips.",
    "You are the liquidity provider for smart money."
];

export const ROASTS_GENERIC = [
    "Mediocre. Just like your trading strategy.",
    "Your portfolio is a diversity hire of bad tokens.",
    "Not enough to be a whale, too much to receive sympathy.",
    "You are the NPC of the Solana ecosystem.",
    "Your wallet has zero main character energy.",
    "Boring. Basic. Broke.",
    "You trade like you hate your future self.",
    "This wallet is the financial equivalent of unseasoned chicken.",
    "Even the blockchain is embarrassed to store this data.",
    "I'd roast you harder, but you're already suffering enough.",
    "You're just... existing. On chain.",
    "Your transactional volume is underwhelming.",
    "This wallet lacks personality. And profit.",
    "You're the background character in everyone else's movie.",
    "Stats: 50% luck, 50% pain, 0% skill.",
    "Your wallet is as interesting as a Terms of Service agreement.",
    "You're just here so you don't get fined.",
    "Average. In every sense of the word.",
    "You're effectively breaking even. Boring.",
    "Show me the loss porn or show me the gains. This is just noise.",
    "You're the person who buys stablecoins hoping they pump.",
    "Your risk tolerance is: Vanilla.",
    "You probably recount your seed phrase to sleep.",
    "This wallet needs a Red Bull.",
    "Start taking risks. Or don't. I don't care.",
    "You're firmly in the mid-curve.",
    "Neither a winner nor a loser. Just a participant.",
    "You got a participation trophy in crypto.",
    "Your wallet history reads like a tax audit.",
    "Do something interesting."
];
